name: Run static tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run static tests on node v22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - run: npm test
      - run: npm run build --if-present
